# CE302 ADVANCED PROGRAMMING TECHNIQUES FOR ENGINEERS

In [ ]:
import numpy as np

## Create the vectors

In [1]:
vect  = np.array([1,2,3])

NameError: name 'np' is not defined

In [ ]:
vect.T

In [ ]:
vect.T.shape

## Create a matrix from the vectors

In [ ]:
vec1 = np.array([1,2,3])
vec2 = np.array([3,4,5])
vec3 = np.array([4,5,6])

In [ ]:
whos

In [ ]:
myMatrice = np.vstack([vec1 , vec2 , vec3])

In [18]:
myMatrice

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
myMatrice.diagonal()

In [ ]:
myMatrice.T

In [ ]:
myMatrice.shape

## Summation

In [12]:
myMatrice + myMatrice

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [ 8, 10, 12]])

In [13]:
np.add( myMatrice , myMatrice)

array([[ 2,  4,  6],
       [ 6,  8, 10],
       [ 8, 10, 12]])

## Subtraction

In [14]:

myMatrice - myMatrice


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Division

In [15]:
myMatrice / myMatrice

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.divide( myMatrice , myMatrice)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Multiplication

In [17]:
myMatrice * myMatrice

array([[ 1,  4,  9],
       [ 9, 16, 25],
       [16, 25, 36]])

In [19]:
myMatrice

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [20]:
np.sqrt( myMatrice * myMatrice )

array([[1., 2., 3.],
       [3., 4., 5.],
       [4., 5., 6.]])

### Dot multiplication

In [21]:
np.dot( myMatrice , myMatrice)

array([[19, 25, 31],
       [35, 47, 59],
       [43, 58, 73]])

In [22]:
np.multiply( myMatrice , myMatrice)

array([[ 1,  4,  9],
       [ 9, 16, 25],
       [16, 25, 36]])

In [23]:
vec1

array([1, 2, 3])

In [24]:
vec1 * vec1

array([1, 4, 9])

In [25]:
np.dot( vec1 , vec1)

14

## Determinant 

In [26]:
np.linalg.det(myMatrice)

0.0

In [27]:
np.linalg.inv( myMatrice)

LinAlgError: Singular matrix

## Linear Equations 

3x + 4y + 5z = 10 

3y - 9z = 0

x + 10z = 10

Let's put them in matrix form

$$ \begin{bmatrix} 3 & 4 & 5 \\ 0 & 3 & -9 \\ 1 & 0 & 10 \end{bmatrix} \times \begin{bmatrix}x\\y\\z\end{bmatrix} =  \begin{bmatrix}10\\0\\10 \end{bmatrix}$$ 


**Remember __the Gauss elimination, Gauss-Jordan elimination, LU decomposition__ ...**

In [28]:
a_matrice = np.array([[3,4,5],[0,3,-9],[1,0,10]])

In [29]:
a_matrice

array([[ 3,  4,  5],
       [ 0,  3, -9],
       [ 1,  0, 10]])

In [30]:
RHS_matrice = np.array([10,0,10])

In [31]:
np.linalg.solve( a_matrice , RHS_matrice)

array([-5.38461538,  4.61538462,  1.53846154])

$$ \frac{\begin{bmatrix} 3 & 4 & 5 \\ 0 & 3 & -9 \\ 1 & 0 & 10 \end{bmatrix} \times \begin{bmatrix}x\\y\\z\end{bmatrix}}{\begin{bmatrix} 3 & 4 & 5 \\ 0 & 3 & -9 \\ 1 & 0 & 10 \end{bmatrix}} = \frac {\begin{bmatrix}10\\0\\10 \end{bmatrix} }{\begin{bmatrix} 3 & 4 & 5 \\ 0 & 3 & -9 \\ 1 & 0 & 10 \end{bmatrix} } $$ 

In [32]:
np.linalg.inv(a_matrice)

array([[ 0.76923077, -1.02564103, -1.30769231],
       [-0.23076923,  0.64102564,  0.69230769],
       [-0.07692308,  0.1025641 ,  0.23076923]])

In [34]:
np.dot( np.linalg.inv( a_matrice), RHS_matrice)

array([-5.38461538,  4.61538462,  1.53846154])

In CE312 class, you'll solve the  [K] . {U} = {P} 

K : stifness matrix

U : Displacement matrix

P : Load matrix

In [35]:
np.linalg.det( a_matrice)

39.000000000000014